### ISSUE TITLE
Data migration failures

### ISSUE THREAD

**Issue by kpudlik** [Constellation-Labs/constellation#1223]
![image.png](https://images.zenhubusercontent.com/5eb008cca482017c0438cc85/5a46707a-6b4d-4412-90e2-b81d3504ff35)

![image.png](https://images.zenhubusercontent.com/5eb008cca482017c0438cc85/359199ac-46e7-4957-bb7d-da4040cab96b)

**Comment by marcinwadon** [comment]
```
2020-05-22 08:11:32,838 [ForkJoinPool-1-worker-0] [] DEBUG o.c.s.SnapshotService - Snapshot written: a92571e0c8090f52ffde115c4c9f5e5ae139b6bc66a05cb984ae649255a207af
...
2020-05-22 08:11:32,854 [ioapp-compute-2] [] DEBUG o.c.d.r.RedownloadService - Removing unaccepted snapshots from disk.
...
2020-05-22 08:11:32,855 [ioapp-compute-2] [] ERROR o.c.i.r.RedownloadPeriodicCheck - Error when executing periodic task: RedownloadPeriodicCheck due: /home/admin/constellation/tmp/710b3dc521/snapshot_infos/a92571e0c8090f52ffde115c4c9f5e5ae139b6bc66a05cb984ae649255a207af
java.nio.file.NoSuchFileException: /home/admin/constellation/tmp/710b3dc521/snapshot_infos/a92571e0c8090f52ffde115c4c9f5e5ae139b6bc66a05cb984ae649255a207af
[...] at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	  at java.nio.file.Files.delete(Files.java:1126)
	  at better.files.File.delete(File.scala:1001)
...
2020-05-22 08:11:32,875 [ForkJoinPool-1-worker-0] [] DEBUG o.c.d.SnapshotTrigger - Attempt snapshot took: 124 millis
2020-05-22 08:11:32,879 [ForkJoinPool-1-worker-0] [] DEBUG o.c.d.SnapshotTrigger - Finished [triggerSnapshot] on thread: ForkJoinPool-1-worker-0 and took 128ms
```

- Snapshot stored on disk
- Snapshot info creating/writing in progress
- In background, redownload service checks if there are things to remove
- **Removed snapshot, didn't remove snapshot info as it doesn't exist yet**
- Snapshot info stored on disk
- End of snapshot creation, end of redownload check round

and after few seconds when node tries to send snapshot to cloud:
- snapshot doesn't exist, but snapshot info exists
