### ISSUE TITLE
SelfAvoidingWalk stackoverflow issue

### ISSUE THREAD

**Issue by marcinwadon** [Constellation-Labs/constellation#1256]
![image.png](https://images.zenhubusercontent.com/57dd18bbe40e5714b16f064a/c247a08e-94bf-471f-b449-d347c29fc722)

**Comment by marcinwadon** [comment]
@buckysballs That change is deployed on mainnet. I'd close this ticket and re-open it if we'll see the error again.

**Comment by marcinwadon** [comment]
@buckysballs still an issue
```
Jun 19 23:42:15 ip-172-31-2-45 start[27213]: java.lang.StackOverflowError
Jun 19 23:42:15 ip-172-31-2-45 start[27213]:         at scala.collection.immutable.HashMap$HashMap1.updated0(HashMap.scala:220)
Jun 19 23:42:15 ip-172-31-2-45 start[27213]:         at scala.collection.immutable.HashMap$HashTrieMap.updated0(HashMap.scala:362)
Jun 19 23:42:15 ip-172-31-2-45 start[27213]:         at scala.collection.immutable.HashMap.updated(HashMap.scala:62)
Jun 19 23:42:15 ip-172-31-2-45 start[27213]:         at scala.collection.immutable.Map$Map4.updated(Map.scala:227)
Jun 19 23:42:15 ip-172-31-2-45 start[27213]:         at scala.collection.immutable.Map$Map4.$plus(Map.scala:228)
Jun 19 23:42:15 ip-172-31-2-45 start[27213]:         at scala.collection.immutable.Map$Map4.$plus(Map.scala:200)
Jun 19 23:42:15 ip-172-31-2-45 start[27213]:         at scala.collection.mutable.MapBuilder.$plus$eq(MapBuilder.scala:32)
Jun 19 23:42:15 ip-172-31-2-45 start[27213]:         at scala.collection.mutable.MapBuilder.$plus$eq(MapBuilder.scala:28)
Jun 19 23:42:15 ip-172-31-2-45 start[27213]:         at scala.collection.TraversableLike.$anonfun$filterImpl$1(TraversableLike.scala:256)
Jun 19 23:42:15 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.$anonfun$foreach$1(MapLike.scala:238)
Jun 19 23:42:15 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.$anonfun$foreach$1(MapLike.scala:238)
Jun 19 23:42:15 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.$anonfun$foreach$1(MapLike.scala:238)
Jun 19 23:42:15 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.$anonfun$foreach$1(MapLike.scala:238)
Jun 19 23:42:15 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.$anonfun$foreach$1(MapLike.scala:238)
Jun 19 23:42:15 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.$anonfun$foreach$1(MapLike.scala:238)
Jun 19 23:42:15 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.$anonfun$foreach$1(MapLike.scala:238)
Jun 19 23:42:15 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.$anonfun$foreach$1(MapLike.scala:238)
Jun 19 23:42:15 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.$anonfun$foreach$1(MapLike.scala:238)
Jun 19 23:42:15 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.$anonfun$foreach$1(MapLike.scala:238)
Jun 19 23:42:15 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.$anonfun$foreach$1(MapLike.scala:238)
Jun 19 23:42:15 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.$anonfun$foreach$1(MapLike.scala:238)
Jun 19 23:42:15 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.$anonfun$foreach$1(MapLike.scala:238)
Jun 19 23:42:15 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.$anonfun$foreach$1(MapLike.scala:238)
Jun 19 23:42:15 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.$anonfun$foreach$1(MapLike.scala:238)
Jun 19 23:42:15 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.$anonfun$foreach$1(MapLike.scala:238)
Jun 19 23:42:16 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.$anonfun$foreach$1(MapLike.scala:238)
Jun 19 23:42:16 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.$anonfun$foreach$1(MapLike.scala:238)
Jun 19 23:42:16 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.$anonfun$foreach$1(MapLike.scala:238)
Jun 19 23:42:16 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.$anonfun$foreach$1(MapLike.scala:238)
Jun 19 23:42:16 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.$anonfun$foreach$1(MapLike.scala:238)
Jun 19 23:42:16 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.$anonfun$foreach$1(MapLike.scala:238)
Jun 19 23:42:16 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.$anonfun$foreach$1(MapLike.scala:238)
Jun 19 23:42:16 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.$anonfun$foreach$1(MapLike.scala:238)
Jun 19 23:42:16 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.$anonfun$foreach$1(MapLike.scala:238)
Jun 19 23:42:16 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.$anonfun$foreach$1(MapLike.scala:238)
Jun 19 23:42:16 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.$anonfun$foreach$1(MapLike.scala:238)
Jun 19 23:42:16 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.$anonfun$foreach$1(MapLike.scala:238)
Jun 19 23:42:16 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.$anonfun$foreach$1(MapLike.scala:238)
Jun 19 23:42:16 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.$anonfun$foreach$1(MapLike.scala:238)
Jun 19 23:42:16 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.$anonfun$foreach$1(MapLike.scala:238)
Jun 19 23:42:16 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.$anonfun$foreach$1(MapLike.scala:238)
Jun 19 23:42:16 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.$anonfun$foreach$1(MapLike.scala:238)
Jun 19 23:42:16 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.$anonfun$foreach$1(MapLike.scala:238)
Jun 19 23:42:16 ip-172-31-2-45 start[27213]:         at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:234)
Jun 19 23:42:16 ip-172-31-2-45 start[27213]:         at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:468)
Jun 19 23:42:16 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.foreach(MapLike.scala:238)
Jun 19 23:42:16 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.foreach(MapLike.scala:238)
Jun 19 23:42:16 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.foreach(MapLike.scala:238)
Jun 19 23:42:16 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.foreach(MapLike.scala:238)
Jun 19 23:42:16 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.foreach(MapLike.scala:238)
Jun 19 23:42:16 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.foreach(MapLike.scala:238)
Jun 19 23:42:16 ip-172-31-2-45 start[27213]:         at scala.collection.MapLike$FilteredKeys.foreach(MapLike.scala:238)
```

**Comment by marcinwadon** [comment]
I see that ``` runWalkFeedbackUpdateSingleNode nodes List(TrustNode(2,0.0,0.0,List(TrustEdge(2,13,1.0,false)``` <--- the list is increasing
