### ISSUE TITLE
Investigate database failures

### ISSUE THREAD

**Issue by ryle-goehausen** [Constellation-Labs/constellation#205]
> java.lang.RuntimeException: Could not open table 105
    at org.iq80.leveldb.impl.TableCache.getTable(TableCache.java:98)
    at org.iq80.leveldb.impl.TableCache.newIterator(TableCache.java:79)
    at org.iq80.leveldb.impl.TableCache.newIterator(TableCache.java:74)
    at org.iq80.leveldb.impl.Level0.get(Level0.java:100)
    at org.iq80.leveldb.impl.Version.get(Version.java:169)
    at org.iq80.leveldb.impl.VersionSet.get(VersionSet.java:223)
    at org.iq80.leveldb.impl.DbImpl.get(DbImpl.java:616)
    at org.iq80.leveldb.impl.DbImpl.get(DbImpl.java:577)
    at org.constellation.LevelDB.getBytes(LevelDB.scala:277)
    at org.constellation.KVDBImpl.get(LevelDB.scala:101)
    at org.constellation.KVDBImpl.update(LevelDB.scala:112)
    at org.constellation.KVDBImpl.updateTransactionCacheData(LevelDB.scala:158)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at akka.actor.TypedActor$MethodCall.apply(TypedActor.scala:146)
    at akka.actor.TypedActor$TypedActor$$anonfun$receive$1.$anonfun$applyOrElse$1(TypedActor.scala:310)
    at akka.actor.TypedActor$TypedActor.withContext(TypedActor.scala:298)
    at akka.actor.TypedActor$TypedActor$$anonfun$receive$1.applyOrElse(TypedActor.scala:306)
    at akka.actor.Actor.aroundReceive(Actor.scala:517)
    at akka.actor.Actor.aroundReceive$(Actor.scala:515)
    at akka.actor.TypedActor$TypedActor.aroundReceive(TypedActor.scala:245)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
    at akka.actor.ActorCell.invoke(ActorCell.scala:557)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
    at akka.dispatch.Mailbox.run(Mailbox.scala:225)
    at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
    at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.io.FileNotFoundException: /home/ryle/tmp/a1cb475/db/000105.sst (No such file or directory)

Caused by: akka.pattern.AskTimeoutException: Recipient[Actor[akka://Constellation/user/KVDB_-155298664#781441977]] had already been terminated. Sender[null] sent the message of type "akka.actor.TypedActor$MethodCall".
	at akka.pattern.AskableActorRef$.internalAsk$extension(AskSupport.scala:291)
	at akka.pattern.AskSupport.ask(AskSupport.scala:78)
	at akka.pattern.AskSupport.ask$(AskSupport.scala:77)
	at akka.pattern.package$.ask(package.scala:42)
	at akka.actor.TypedActor$TypedActorInvocationHandler.invoke(TypedActor.scala:432)
	... 23 more
java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy3.updateTransactionCacheData(Unknown Source)
	at org.constellation.primitives.Schema$Edge.storeTransactionCacheData(Schema.scala:294)
	at org.constellation.primitives.Schema$Transaction.store(Schema.scala:211)
	at org.constellation.consensus.EdgeProcessor$.$anonfun$acceptCheckpoint$12(EdgeProcessor.scala:330)
	at org.constellation.consensus.EdgeProcessor$.$anonfun$acceptCheckpoint$12$adapted(EdgeProcessor.scala:326)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at org.constellation.consensus.EdgeProcessor$.acceptCheckpoint(EdgeProcessor.scala:326)
	at org.constellation.primitives.ThreadSafeTipService.$anonfun$accept$1(EdgeDAO.scala:140)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.Try$.apply(Try.scala:209)
	at org.constellation.primitives.ThreadSafeTipService.accept(EdgeDAO.scala:140)
	at org.constellation.p2p.PeerAPI.$anonfun$postEndpoints$24(PeerAPI.scala:171)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:654)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: akka.pattern.AskTimeoutException: Recipient[Actor[akka://Constellation/user/KVDB_-155298664#781441977]] had already been terminated. Sender[null] sent the message of type "akka.actor.TypedActor$MethodCall".
	at akka.pattern.AskableActorRef$.internalAsk$extension(AskSupport.scala:291)
	at akka.pattern.AskSupport.ask(AskSupport.scala:78)
	at akka.pattern.AskSupport.ask$(AskSupport.scala:77)
	at akka.pattern.package$.ask(package.scala:42)
	at akka.actor.TypedActor$TypedActorInvocationHandler.invoke(TypedActor.scala:432)
	... 23 more
java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy3.updateTransactionCacheData(Unknown Source)
	at org.constellation.primitives.Schema$Edge.storeTransactionCacheData(Schema.scala:294)
	at org.constellation.primitives.Schema$Transaction.store(Schema.scala:211)
	at org.constellation.consensus.EdgeProcessor$.$anonfun$acceptCheckpoint$12(EdgeProcessor.scala:330)
	at org.constellation.consensus.EdgeProcessor$.$anonfun$acceptCheckpoint$12$adapted(EdgeProcessor.scala:326)
	at scala.collection.immutable.List.foreach(List.scala:388)
	at org.constellation.consensus.EdgeProcessor$.acceptCheckpoint(EdgeProcessor.scala:326)
	at org.constellation.primitives.ThreadSafeTipService.$anonfun$accept$1(EdgeDAO.scala:140)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.Try$.apply(Try.scala:209)
	at org.constellation.primitives.ThreadSafeTipService.accept(EdgeDAO.scala:140)
	at org.constellation.p2p.PeerAPI.$anonfun$postEndpoints$24(PeerAPI.scala:171)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:654)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:288)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: akka.pattern.AskTimeoutException: Recipient[Actor[akka://Constellation/user/KVDB_-155298664#781441977]] had already been terminated. Sender[null] sent the message of type "akka.actor.TypedActor$MethodCall".
	at akka.pattern.AskableActorRef$.internalAsk$extension(AskSupport.scala:291)
	at akka.pattern.AskSupport.ask(AskSupport.scala:78)
	at akka.pattern.AskSupport.ask$(AskSupport.scala:77)
	at akka.pattern.package$.ask(package.scala:42)
	at akka.actor.TypedActor$TypedActorInvocationHandler.invoke(TypedActor.scala:432)
	... 23 more

This may have been influenced by recent changes to happen more? But this has been observed before.

**Comment by ryle-goehausen** [comment]
Using SwayDB now not akka/leveldb
