### ISSUE TITLE
Snapshot not found stacktrace polute execution of e2e

### ISSUE THREAD

**Issue by wkoszycki** [Constellation-Labs/constellation#450]
When performing `e2e` test we are observing:

```
java.lang.RuntimeException: 3ae2a No snapshot found at /home/developer/code/constellation/tmp/3ae2a670d7/snapshots/5eea692e289b593018b473a6969739378090d8063a861661ce2f0d34b3ad01fd
	at org.constellation.consensus.Snapshot$.$anonfun$loadSnapshotBytes$1(EdgeProcessor.scala:398)
	at scala.util.Try$.apply(Try.scala:213)
	at constellation.package$.tryWithMetric(package.scala:188)
	at org.constellation.consensus.Snapshot$.loadSnapshotBytes(EdgeProcessor.scala:390)
	at org.constellation.util.CommonEndpoints.$anonfun$commonEndpoints$20(CommonEndpoints.scala:80)
	at scala.Option.flatMap(Option.scala:188)
	at org.constellation.util.CommonEndpoints.$anonfun$commonEndpoints$19(CommonEndpoints.scala:80)
	at cats.effect.internals.IORunLoop$.cats$effect$internals$IORunLoop$$loop(IORunLoop.scala:87)
	at cats.effect.internals.IORunLoop$.start(IORunLoop.scala:34)
	at cats.effect.IO.unsafeRunAsync(IO.scala:258)
	at cats.effect.IO.unsafeToFuture(IO.scala:345)
	at org.constellation.util.CommonEndpoints.$anonfun$commonEndpoints$22(CommonEndpoints.scala:84)
	at akka.http.scaladsl.server.directives.FutureDirectives.$anonfun$onComplete$2(FutureDirectives.scala:37)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$mapRequestContext$2(BasicDirectives.scala:43)
	at akka.http.scaladsl.server.directives.BasicDirectives.$anonfun$textract$2(BasicDirectives.scala:159)
	at akka.http.scaladsl.server.RouteConcatenation$RouteWithConcatenation.$anonfun$$tilde$2(RouteConcatenation.scala:47)
	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
	at akka.http.scaladsl.util.FastFuture$.flatMap$extension(FastFuture.scala:26)
```
`storedSnapshot` should check first whether snapshot  exist before diving into reading a file, proper response (404) should also be returned or 500 if snapshot info is stored but file is missing.

**Comment by wkoszycki** [comment]
@buckysballs please close
